export default [
  {
    id: 'Bamboo watch',
    img: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
    name: 'Bamboo watch',
    categorieLabel: 'sell',
    categorie: 'Accessories',
    price: '100',
  },
  {
    id: 'Black watch',
    img: 'https://primefaces.org/cdn/primeng/images/demo/product/black-watch.jpg',
    name: 'Black watch',
    categorieLabel: 'sell',
    categorie: 'Accessories',
    price: '200',
  },
  {
    id: 'Blue Band',
    img: 'https://primefaces.org/cdn/primeng/images/demo/product/blue-band.jpg',
    name: 'Blue Band',
    categorieLabel: 'sell',
    categorie: 'Accessories',
    price: '170',
  },
  {
    id: 'Galaxy Earings',
    img: 'https://primefaces.org/cdn/primeng/images/demo/product/galaxy-earrings.jpg',
    name: 'Galaxy Earings',
    categorieLabel: 'sell',
    categorie: 'Accessories',
    price: '140',
  },
  {
    id: 'Game Controller',
    img: 'https://primefaces.org/cdn/primeng/images/demo/product/game-controller.jpg',
    name: 'Game Controller',
    categorieLabel: 'sell',
    categorie: 'Electronics',
    price: '70',
  },
  {
    id: 'Gaming set',
    img: 'https://primefaces.org/cdn/primeng/images/demo/product/gaming-set.jpg',
    name: 'Gaming set',
    categorieLabel: 'sell',
    categorie: 'Electronics',
    price: '135',
  },
  {
    id: 'Blue t-shirt',
    img: 'https://primefaces.org/cdn/primeng/images/demo/product/blue-t-shirt.jpg',
    name: 'Blue t-shirt',
    categorieLabel: 'sell',
    categorie: 'Clothes',
    price: '53',
  },
  {
    id: 'Brown purse',
    img: 'https://primefaces.org/cdn/primeng/images/demo/product/brown-purse.jpg',
    name: 'Brown purse',
    categorieLabel: 'sell',
    categorie: 'Accessories',
    price: '150',
  },
  {
    id: 'Chackra bracelet',
    img: 'https://primefaces.org/cdn/primeng/images/demo/product/chakra-bracelet.jpg',
    name: 'Chackra bracelet',
    categorieLabel: 'sell',
    categorie: 'Accessories',
    price: '23',
  },
];
